options:
  logging: CLOUD_LOGGING_ONLY  # Or specify 'build.logs_bucket' for Cloud Storage logging


steps:
# Build the Vue.js application
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/terraform-429505/my-vue-app:latest', 'frontend']

# Build the PHP backend
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/terraform-429505/my-php:latest', 'backend']

# Optionally, you can push the images to Google Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/terraform-429505/my-vue-app:latest']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/terraform-429505/my-php:latest']



images:
- 'gcr.io/terraform-429505/my-vue-app:latest'
- 'gcr.io/terraform-429505/my-php:latest'
