version: '3.3'

services:
  combined-app:
    build:
      context: .
      dockerfile: backend/Dockerfile  # Start with the backend Dockerfile
    image: gcr.io/terraform-429505/my-combined-app:latest
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: |
      sh -c "
      cp -r /app/my-vue-app/dist/* /var/www/html/frontend/ &&
      apache2-foreground
      "
    image: gcr.io/terraform-429505/my-combined-app-frontend:latest
    depends_on:
      - combined-app

