version: '3.8'

services:
  php:
    build:
      context: ./backend
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html

  frontend:
    build:
      context: ./frontend
    ports:
      - "5000:5000"
